# Generated by Django 5.2.8 on 2025-11-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aaboutus',
            new_name='Aboutus',
        ),
    ]
