# Generated by Django 5.2.8 on 2025-11-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_rename_aaboutus_aboutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='descriptipn',
            new_name='description',
        ),
    ]
