# Generated by Django 5.2.8 on 2025-11-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_rename_descriptipn_aboutus_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='slider_images/')),
            ],
        ),
    ]
