# Generated by Django 5.2.8 on 2025-11-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_sliderimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='Description',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
