# Generated by Django 5.2.8 on 2025-11-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_remove_sliderimage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
