# Generated by Django 5.2.8 on 2025-11-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_alter_sliderimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='title',
        ),
    ]
