# Generated by Django 5.2.8 on 2025-11-19 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='feedback_images/'),
            preserve_default=False,
        ),
    ]
