# Generated by Django 5.2.8 on 2025-11-21 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_feedback_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='booking_data',
            new_name='bookingdate',
        ),
        migrations.RenameField(
            model_name='booktable',
            old_name='phone_number',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='booktable',
            old_name='total_person',
            new_name='totalperson',
        ),
        migrations.RenameField(
            model_name='booktable',
            old_name='name',
            new_name='username',
        ),
    ]
