# Generated by Django 5.2.8 on 2025-11-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_rename_booking_data_booktable_bookingdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='phonenumber',
            field=models.CharField(),
        ),
    ]
