# Generated by Django 5.2.8 on 2025-11-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0013_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='location',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
