# Generated by Django 5.2.8 on 2025-11-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0014_contactus_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(default='', max_length=20000)),
                ('twitter', models.CharField(default='', max_length=20000)),
                ('linkedin', models.CharField(default='', max_length=20000)),
                ('instagram', models.CharField(default='', max_length=20000)),
                ('pinterest', models.CharField(default='', max_length=20000)),
            ],
        ),
    ]
