# Generated by Django 5.2.8 on 2025-11-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0015_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening_Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_day', models.CharField(max_length=20)),
                ('opening_time', models.CharField(max_length=200)),
            ],
        ),
    ]
